### ISSUE TITLE
udev installation stalls

### ISSUE THREAD

**Issue by entertheabyss** [mfwitten/udev#1]
when i try to upgrade my system with apt-get upgrade or try to run ~$ dpkg --configure -a
the process hangs and does not move on to the next application

    root@debian:/home/user# dpkg --configure -a
    Setting up udev (215-17+deb8u5) ...
    addgroup: The group `input' already exists as a system group. Exiting.

or if i run groupdel input

    Adding group `input' (GID 101) ...
    Done.

in both cases it hangs i tried waiting a few hours
not sure what to do

**Comment by mfwitten** [comment]
Alas, I apologize that I am unable to help you; this personal repository is merely an ancient fork.

I hope you have figured out how to fix your issue; if not, I suggest asking questions in a forum dedicated to Debian.

May I close this issue?
